### ISSUE TITLE
mock the reporter such that undef messages cause a failed test

### ISSUE THREAD

**Issue by stdweird** [quattor/maven-tools#74]
See https://github.com/quattor/CAF/issues/134 and https://github.com/quattor/CAF/pull/135

**Comment by jouvin** [comment]
I don't know if this should be considered an issue or a feature. I came through this problem with a component using `CAF::Service` without mocking it in the unit tests (something done in most components using it...). `CAF::Service` seems to pass an undef string when `stdout` and `stderr` are empty (I haven't checked but I guess this is due to some `CAF::Process` mocking): look at the traceback in https://github.com/quattor/CAF/issues/134. Should we add the complexity in this context of converting all the undef arguments to an empty string or is it better to have the reporter doing the thing... Personnally I tend to think the proposed behaviour is the right one: having the reporter failing a test because an argument is empty can be very confusing and difficult to troubleshoot...

**Comment by stdweird** [comment]
then we should improve the mocking. the workaround (esp in the non-mocked reporter) can be accepted to prevent failures, but they indicate a bug, esp in the non-mocked reporter (unless you know a valid usecase where an undef is passed to the reporter).

**Comment by jouvin** [comment]
Is there a mocked reporter? I thought there was none...
